#https://colab.research.google.com/drive/11KSZ2t5_AodyXFVyVlRjs8D9uzvawJ3x?usp=sharing
# Домашнее задание к 7 уроку.

**Дедлайн: 23.12.2020**

colab: https://colab.research.google.com/drive/1KLD5pDCa0ka_g1U4D2ExihaaEwXzfTPW?usp=sharing

**ФОРМАТ ОТЧЕТНОСТИ:** pdf-файл с решенными задачами (задачи 2-9), ноутбук с проверкой решения этих задач (при помощи numpy), и pdf файл с отчетом по 1-ой задаче (краткий пересказ статьи). Вы можете оформить решения с использованием Markdown (писать текст прямо в юпитер ноутбуке), Latex, Word или же решить в тетради и сформировать pdf из фото.

Итого: 2 pdf файла.

Все задания необходимо выполнять ВРУЧНУЮ. А также проверить корректность полученных результатов с использованием Numpy.

Туториал как писать "Latex-формулы" прямо в Юпитере:
https://www.youtube.com/watch?v=vSc25kdgecg

Ноутбук с примером формул: https://nbviewer.jupyter.org/github/postlogist/course_opt/blob/master/jupyter_tutorial/02_markdown.ipynb


## Пример


Найдем ранг матрицы 

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
2 & 5 & 8 & 11 & 14\\ 
3 & 9 & 14 & 20 & 26\\ 
5 & 14 & 22 & 31 & 40
\end{pmatrix}.$$

Четвертая строка является суммой второй и третьей строк, а значит, ее можно отбросить:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
2 & 5 & 8 & 11 & 14\\ 
3 & 9 & 14 & 20 & 26
\end{pmatrix}.$$

Из второй и третьей строк вычтем первую, умноженную на $2$ и $3$ соответственно:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
0 & 1 & 2 & 3 & 4\\ 
0 & 2 & 5 & 8 & 11
\end{pmatrix}.$$

И вычтем из третьей строки вторую, умноженную на $2$:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
0 & 1 & 2 & 3 & 4\\ 
0 & 0 & 1 & 2 & 3
\end{pmatrix}.$$

Таким образом, ранг матрицы равен $3$.

In [ ]:
# Проверка

import numpy as np
a = [1, 2, 3, 4, 5]
b = [2, 5, 8, 11, 14]
c = [3, 9, 14, 20, 26]
d = [5, 14, 22, 31, 40]

x = np.array([a, b, c, d])
r = np.linalg.matrix_rank(x)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3


# Задачи

**1.** Прочитать статью http://www.scielo.org.mx/pdf/cys/v18n3/v18n3a7.pdf и сделать следующее:

- Написать кратко (не более 300 слов (минимум 100), отчет в формате pdf) о различиях между cosine similarity и soft similarity. Привести примеры использования и написать собственный пример вычисления cosine similarity и soft similarity для произвольных векторов (не брать вектора из статьи! надо самим придумать координаты/размерность векторов)

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    
__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.


__6.__ Вычислить определитель (используйте любой удобный для вас способ вычисления определителя: через миноры, через перестановки или другой):

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
8 & 4 & 6\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
2 & 3 & 4\\ 
5 & 6 & 7\\ 
8 & 9 & 10
\end{vmatrix}.$$


__7.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   
__8.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__9.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

# Доп материалы
1. [Способы задать матрицу в NumPy](https://docs.scipy.org/doc/numpy-1.10.1/user/basics.creation.html).
2. [numpy.transpose](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.transpose.html).
3. [array.T](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.ndarray.T.html).
4. [Перемножение матриц в NumPy](https://docs.scipy.org/doc/numpy-1.10.0/reference/routines.linalg.html#matrix-and-vector-products).

5. [Определитель матрицы в NumPy](https://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.linalg.det.html)

6. [Ранг матрицы в NumPy](https://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.linalg.matrix_rank.html)

7. [Обращение матриц в NumPy](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)

In [2]:
#Задача №2
import numpy as np
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]]) 

print(f'Матрица A\n{a}\n')
print(f'Матрица B\n{b}\n')
print(f'Матрица С = A + B\n{a + b}')
print(f'Матрица D = A * B\n{a * b}')

Матрица A
[[ 1 -2]
 [ 3  0]]

Матрица B
[[ 4 -1]
 [ 0  5]]

Матрица С = A + B
[[ 5 -3]
 [ 3  5]]
Матрица D = A * B
[[4 2]
 [0 0]]


In [3]:
#Задача №3
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])  
c = np.array([[2, -4], [1, 1]])
print(f'Матрица D = 3*A - 2*B + 4*С\n{3*a - 2 * b + 4 * c}')

Матрица D = 3*A - 2*B + 4*С
[[ 11  -5]
 [  9 -12]]


In [4]:
#Задача №4
a = np.array([[4, 1], [5, -2], [2, 3]])
b = a.T
print(f'A*AT:\n{np.dot(a, b)}')
print(f'AT*A:\n{np.dot(b, a)}')

A*AT:
[[17 18 11]
 [18 29  4]
 [11  4 13]]
AT*A:
[[45  0]
 [ 0 14]]


In [5]:
#Задача №5 
# Вариант 1
matrix1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix2 = [[2, 3, 4], [6,7,3], [4, 5, 9]]
res = [[0 for x in range(3)] for y in range(3)] 
for i in range(len(matrix1)):
    for j in range(len(matrix2[0])):
        for k in range(len(matrix2)):
            # приведенная матрица
            res[i][j] += matrix1[i][k] * matrix2[k][j]
print (res)

#Вариант 2
def func():  
    r1 = int(input('Элементов в строке в матрицы1: '))
    c1 = int(input('Элементов в солбце в матрицы1: ')) 
    r2 = int(input('Элементов в строке в матрицы2: '))
    c2 = int(input('Элементов в солбце в матрицы2: '))
    print('Вводим элементы матрицы A')
    A = []
    for i in range(r1) :
        A.append([])
        for j in range(c1) :
            A[i].append(int(input()))        
    print('A = ')
    for q in A :
        print(q)
    print('Вводим элементы матрицы B')
    B = []
    for q in range(r2) :
        B.append([])
        for w in range(c2) :
            B[q].append(int(input()))
    print('B = ')
    for q in B :
        print(q)
    s=0     #сумма
    t=[]    #временная матрица
    C=[] # конечная матрица
    if len(B)!=len(A[0]):
        print ("Матрицы не могут быть перемножены")        
    else:
        r1=len(A) #количество строк в первой матрице
        c1=len(A[0]) #Количество столбцов в 1   
        r2=c1           #и строк во 2ой матрице
        c2=len(B[0])  # количество столбцов во 2ой матрице
        for z in range(0,r1):
            for j in range(0,c2):
                for i in range(0,c1):
                   s=s+A[z][i]*B[i][j]
                t.append(s)
                s=0
            C.append(t)
            t=[]           
    return C

[[26, 32, 37], [62, 77, 85], [98, 122, 133]]


In [14]:
#Задача №6
import numpy as np
a = np.array([[8, 4, 6], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

b = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])
print(f'Матрица:\n{b}')
print(f'Определитель:\n{np.linalg.det(b):.0f}')

Матрица:
[[8 4 6]
 [0 5 1]
 [0 0 9]]
Определитель:
360
Матрица:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
Определитель:
0


In [17]:
#8
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]], dtype=float)
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ -2.   7.  -3.]
 [  4. -14.   6.]
 [ -3.   7.  13.]]
Определитель:
0


In [ ]:
#8 продолжение (определитель равен 0, соответственно обратной матрицы не существует, выходит что матрица a вырождена)
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]], dtype=float)
b = np.linalg.inv(a)
print(f'Матрица A:\n{a}\n')
print(f'Матрица B, обратная к A:\n{b}\n')
print(f'Матрица AB (должна быть единичной):\n{a.dot(b)}')

In [20]:
#Задача 9
x = [1, 2, 3]
y = [1, 1, 1]
z = [2, 3, 4]
a = np.array([x, y, z])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы а: {r}')

Ранг матрицы а: 2


In [21]:
#Задача 9 (часть 2)
x = [0, 0, 2, 1]
y = [0, 0, 1, 1]
z = [0, 0, 4, 3]
q = [2, 3, 5, 6]
b = np.array([x, y, z, q])
r = np.linalg.matrix_rank(b)

print(f'Ранг матрицы b: {r}')

Ранг матрицы b: 3
